global:
  resolve_timeout: 5m
  slack_api_url: 'https://hooks.slack.com/services/your_slack_api_token'
  smtp_smarthost: 'your_smtp_smarthost:587'
  smtp_from: 'your_smtp_from'
  smtp_auth_username: 'your_smtp_user'
  smtp_auth_password: 'your_smtp_pass'
templates:
- '/etc/alertmanager/template/*.tmpl'
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: default-receiver
  routes:
  - match:
      alertname: Watchdog
    receiver: 'null'
inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  # Apply inhibition if the alertname is the same.
  equal: ['alertname', 'cluster', 'service']
receivers:
- name: 'default-receiver'
  slack_configs:
  - channel: '#your_slack_channel'
    title: |-
      [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}]{{ .CommonLabels.alertname }}
    text: >-
      *Alert Message*: {{ .CommonAnnotations.message }}

      {{ if .CommonAnnotations.runbook_url }} *Runbook Link*: <{{ .CommonAnnotations.runbook_url }}|:notebook_with_decorative_cover:>{{ end }}

      {{ if .CommonAnnotations.grafana_url }} *Grafana Link*: <{{ .CommonAnnotations.grafana_url }}|:chart_with_upwards_trend:>{{ end }}

      {{ with index .Alerts 0 -}} *Prometheus Link* <{{ .GeneratorURL }}|:chart_with_upwards_trend:> {{ end }}

    send_resolved: true
  email_configs:
  - to: 'your_alert_email_address'
    send_resolved: true
- name: 'null'
