apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  datasources.yaml: |-
    apiVersion: 1

    datasources:
      - name: prometheus
        type: prometheus
        access: proxy
        orgId: 1
        editable: false
        url: http://prometheus-k8s.CUSTOM_NAMESPACE.svc:9090
        version: 1

      - name: Loki
        type: loki
        access: proxy
        url: http://loki.CUSTOM_NAMESPACE.svc:3100
        editable: false
